# Generated by Django 3.2.9 on 2021-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_contact_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(default='0.jpeg', upload_to='media'),
        ),
    ]
