# Generated by Django 3.2.9 on 2021-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rooms_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_type',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_description',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.FloatField(default=100.0),
        ),
    ]
