# Generated by Django 3.2.9 on 2021-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=2, help_text='Name of the sender', max_length=100),
            preserve_default=False,
        ),
    ]
